package shop.mode;

import shop.mode.extension.CategoryItemExtension;
import shop.mode.mapper.CategoryItemMapper;

public class CategoryItem extends CategoryItemExtension implements shop.mode.ORM.POJOMapper<CategoryItemMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_item.category_item_id
     *
     * @mbg.generated
     */
    private Long category_item_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_item.category_name
     *
     * @mbg.generated
     */
    private String category_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_item.category_id
     *
     * @mbg.generated
     */
    private Long category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_item.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_item.category_item_id
     *
     * @return the value of category_item.category_item_id
     *
     * @mbg.generated
     */
    public Long getCategory_item_id() {
        return category_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_item.category_item_id
     *
     * @param category_item_id the value for category_item.category_item_id
     *
     * @mbg.generated
     */
    public void setCategory_item_id(Long category_item_id) {
        this.category_item_id = category_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_item.category_name
     *
     * @return the value of category_item.category_name
     *
     * @mbg.generated
     */
    public String getCategory_name() {
        return category_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_item.category_name
     *
     * @param category_name the value for category_item.category_name
     *
     * @mbg.generated
     */
    public void setCategory_name(String category_name) {
        this.category_name = category_name == null ? null : category_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_item.category_id
     *
     * @return the value of category_item.category_id
     *
     * @mbg.generated
     */
    public Long getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_item.category_id
     *
     * @param category_id the value for category_item.category_id
     *
     * @mbg.generated
     */
    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_item.icon
     *
     * @return the value of category_item.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_item.icon
     *
     * @param icon the value for category_item.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}