package shop.mode;

import shop.mode.extension.CategoryExtension;
import shop.mode.mapper.CategoryMapper;

public class Category extends CategoryExtension implements shop.mode.ORM.POJOMapper<CategoryMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbg.generated
     */
    private Long category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.menu_id
     *
     * @mbg.generated
     */
    private Integer menu_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbg.generated
     */
    public Long getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param category_id the value for category.category_id
     *
     * @mbg.generated
     */
    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.menu_id
     *
     * @return the value of category.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenu_id() {
        return menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.menu_id
     *
     * @param menu_id the value for category.menu_id
     *
     * @mbg.generated
     */
    public void setMenu_id(Integer menu_id) {
        this.menu_id = menu_id;
    }
}