package shop.mode;

import java.util.ArrayList;
import java.util.List;
import shop.mode.base.BaseExample;

public class CouponExample implements BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public CouponExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idEqualTo(String value) {
            addCriterion("coupon_id =", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotEqualTo(String value) {
            addCriterion("coupon_id <>", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThan(String value) {
            addCriterion("coupon_id >", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_id >=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThan(String value) {
            addCriterion("coupon_id <", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThanOrEqualTo(String value) {
            addCriterion("coupon_id <=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLike(String value) {
            addCriterion("coupon_id like", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotLike(String value) {
            addCriterion("coupon_id not like", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIn(List<String> values) {
            addCriterion("coupon_id in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotIn(List<String> values) {
            addCriterion("coupon_id not in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idBetween(String value1, String value2) {
            addCriterion("coupon_id between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotBetween(String value1, String value2) {
            addCriterion("coupon_id not between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoIsNull() {
            addCriterion("coupon_info is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoIsNotNull() {
            addCriterion("coupon_info is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoEqualTo(String value) {
            addCriterion("coupon_info =", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoNotEqualTo(String value) {
            addCriterion("coupon_info <>", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoGreaterThan(String value) {
            addCriterion("coupon_info >", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_info >=", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoLessThan(String value) {
            addCriterion("coupon_info <", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoLessThanOrEqualTo(String value) {
            addCriterion("coupon_info <=", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoLike(String value) {
            addCriterion("coupon_info like", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoNotLike(String value) {
            addCriterion("coupon_info not like", value, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoIn(List<String> values) {
            addCriterion("coupon_info in", values, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoNotIn(List<String> values) {
            addCriterion("coupon_info not in", values, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoBetween(String value1, String value2) {
            addCriterion("coupon_info between", value1, value2, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_infoNotBetween(String value1, String value2) {
            addCriterion("coupon_info not between", value1, value2, "coupon_info");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountIsNull() {
            addCriterion("coupon_amount is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountIsNotNull() {
            addCriterion("coupon_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountEqualTo(Long value) {
            addCriterion("coupon_amount =", value, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountNotEqualTo(Long value) {
            addCriterion("coupon_amount <>", value, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountGreaterThan(Long value) {
            addCriterion("coupon_amount >", value, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_amount >=", value, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountLessThan(Long value) {
            addCriterion("coupon_amount <", value, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountLessThanOrEqualTo(Long value) {
            addCriterion("coupon_amount <=", value, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountIn(List<Long> values) {
            addCriterion("coupon_amount in", values, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountNotIn(List<Long> values) {
            addCriterion("coupon_amount not in", values, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountBetween(Long value1, Long value2) {
            addCriterion("coupon_amount between", value1, value2, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_amountNotBetween(Long value1, Long value2) {
            addCriterion("coupon_amount not between", value1, value2, "coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeIsNull() {
            addCriterion("coupon_start_time is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeIsNotNull() {
            addCriterion("coupon_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeEqualTo(String value) {
            addCriterion("coupon_start_time =", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeNotEqualTo(String value) {
            addCriterion("coupon_start_time <>", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeGreaterThan(String value) {
            addCriterion("coupon_start_time >", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_start_time >=", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeLessThan(String value) {
            addCriterion("coupon_start_time <", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeLessThanOrEqualTo(String value) {
            addCriterion("coupon_start_time <=", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeLike(String value) {
            addCriterion("coupon_start_time like", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeNotLike(String value) {
            addCriterion("coupon_start_time not like", value, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeIn(List<String> values) {
            addCriterion("coupon_start_time in", values, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeNotIn(List<String> values) {
            addCriterion("coupon_start_time not in", values, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeBetween(String value1, String value2) {
            addCriterion("coupon_start_time between", value1, value2, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_timeNotBetween(String value1, String value2) {
            addCriterion("coupon_start_time not between", value1, value2, "coupon_start_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeIsNull() {
            addCriterion("coupon_end_time is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeIsNotNull() {
            addCriterion("coupon_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeEqualTo(String value) {
            addCriterion("coupon_end_time =", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeNotEqualTo(String value) {
            addCriterion("coupon_end_time <>", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeGreaterThan(String value) {
            addCriterion("coupon_end_time >", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_end_time >=", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeLessThan(String value) {
            addCriterion("coupon_end_time <", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeLessThanOrEqualTo(String value) {
            addCriterion("coupon_end_time <=", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeLike(String value) {
            addCriterion("coupon_end_time like", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeNotLike(String value) {
            addCriterion("coupon_end_time not like", value, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeIn(List<String> values) {
            addCriterion("coupon_end_time in", values, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeNotIn(List<String> values) {
            addCriterion("coupon_end_time not in", values, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeBetween(String value1, String value2) {
            addCriterion("coupon_end_time between", value1, value2, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_end_timeNotBetween(String value1, String value2) {
            addCriterion("coupon_end_time not between", value1, value2, "coupon_end_time");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlIsNull() {
            addCriterion("coupon_share_url is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlIsNotNull() {
            addCriterion("coupon_share_url is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlEqualTo(String value) {
            addCriterion("coupon_share_url =", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlNotEqualTo(String value) {
            addCriterion("coupon_share_url <>", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlGreaterThan(String value) {
            addCriterion("coupon_share_url >", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_share_url >=", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlLessThan(String value) {
            addCriterion("coupon_share_url <", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlLessThanOrEqualTo(String value) {
            addCriterion("coupon_share_url <=", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlLike(String value) {
            addCriterion("coupon_share_url like", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlNotLike(String value) {
            addCriterion("coupon_share_url not like", value, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlIn(List<String> values) {
            addCriterion("coupon_share_url in", values, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlNotIn(List<String> values) {
            addCriterion("coupon_share_url not in", values, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlBetween(String value1, String value2) {
            addCriterion("coupon_share_url between", value1, value2, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_share_urlNotBetween(String value1, String value2) {
            addCriterion("coupon_share_url not between", value1, value2, "coupon_share_url");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeIsNull() {
            addCriterion("coupon_start_fee is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeIsNotNull() {
            addCriterion("coupon_start_fee is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeEqualTo(String value) {
            addCriterion("coupon_start_fee =", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeNotEqualTo(String value) {
            addCriterion("coupon_start_fee <>", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeGreaterThan(String value) {
            addCriterion("coupon_start_fee >", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_start_fee >=", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeLessThan(String value) {
            addCriterion("coupon_start_fee <", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeLessThanOrEqualTo(String value) {
            addCriterion("coupon_start_fee <=", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeLike(String value) {
            addCriterion("coupon_start_fee like", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeNotLike(String value) {
            addCriterion("coupon_start_fee not like", value, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeIn(List<String> values) {
            addCriterion("coupon_start_fee in", values, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeNotIn(List<String> values) {
            addCriterion("coupon_start_fee not in", values, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeBetween(String value1, String value2) {
            addCriterion("coupon_start_fee between", value1, value2, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_start_feeNotBetween(String value1, String value2) {
            addCriterion("coupon_start_fee not between", value1, value2, "coupon_start_fee");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countIsNull() {
            addCriterion("coupon_total_count is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countIsNotNull() {
            addCriterion("coupon_total_count is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countEqualTo(Long value) {
            addCriterion("coupon_total_count =", value, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countNotEqualTo(Long value) {
            addCriterion("coupon_total_count <>", value, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countGreaterThan(Long value) {
            addCriterion("coupon_total_count >", value, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_total_count >=", value, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countLessThan(Long value) {
            addCriterion("coupon_total_count <", value, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countLessThanOrEqualTo(Long value) {
            addCriterion("coupon_total_count <=", value, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countIn(List<Long> values) {
            addCriterion("coupon_total_count in", values, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countNotIn(List<Long> values) {
            addCriterion("coupon_total_count not in", values, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countBetween(Long value1, Long value2) {
            addCriterion("coupon_total_count between", value1, value2, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_total_countNotBetween(Long value1, Long value2) {
            addCriterion("coupon_total_count not between", value1, value2, "coupon_total_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countIsNull() {
            addCriterion("coupon_remain_count is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countIsNotNull() {
            addCriterion("coupon_remain_count is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countEqualTo(Long value) {
            addCriterion("coupon_remain_count =", value, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countNotEqualTo(Long value) {
            addCriterion("coupon_remain_count <>", value, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countGreaterThan(Long value) {
            addCriterion("coupon_remain_count >", value, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_remain_count >=", value, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countLessThan(Long value) {
            addCriterion("coupon_remain_count <", value, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countLessThanOrEqualTo(Long value) {
            addCriterion("coupon_remain_count <=", value, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countIn(List<Long> values) {
            addCriterion("coupon_remain_count in", values, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countNotIn(List<Long> values) {
            addCriterion("coupon_remain_count not in", values, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countBetween(Long value1, Long value2) {
            addCriterion("coupon_remain_count between", value1, value2, "coupon_remain_count");
            return (Criteria) this;
        }

        public Criteria andCoupon_remain_countNotBetween(Long value1, Long value2) {
            addCriterion("coupon_remain_count not between", value1, value2, "coupon_remain_count");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}