package shop.mode;

import shop.mode.extension.CouponExtension;
import shop.mode.mapper.CouponMapper;

public class Coupon extends CouponExtension implements shop.mode.ORM.POJOMapper<CouponMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_id
     *
     * @mbg.generated
     */
    private String coupon_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_info
     *
     * @mbg.generated
     */
    private String coupon_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_amount
     *
     * @mbg.generated
     */
    private Long coupon_amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_start_time
     *
     * @mbg.generated
     */
    private String coupon_start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_end_time
     *
     * @mbg.generated
     */
    private String coupon_end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_share_url
     *
     * @mbg.generated
     */
    private String coupon_share_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_start_fee
     *
     * @mbg.generated
     */
    private String coupon_start_fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_total_count
     *
     * @mbg.generated
     */
    private Long coupon_total_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_remain_count
     *
     * @mbg.generated
     */
    private Long coupon_remain_count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_id
     *
     * @return the value of coupon.coupon_id
     *
     * @mbg.generated
     */
    public String getCoupon_id() {
        return coupon_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_id
     *
     * @param coupon_id the value for coupon.coupon_id
     *
     * @mbg.generated
     */
    public void setCoupon_id(String coupon_id) {
        this.coupon_id = coupon_id == null ? null : coupon_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_info
     *
     * @return the value of coupon.coupon_info
     *
     * @mbg.generated
     */
    public String getCoupon_info() {
        return coupon_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_info
     *
     * @param coupon_info the value for coupon.coupon_info
     *
     * @mbg.generated
     */
    public void setCoupon_info(String coupon_info) {
        this.coupon_info = coupon_info == null ? null : coupon_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_amount
     *
     * @return the value of coupon.coupon_amount
     *
     * @mbg.generated
     */
    public Long getCoupon_amount() {
        return coupon_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_amount
     *
     * @param coupon_amount the value for coupon.coupon_amount
     *
     * @mbg.generated
     */
    public void setCoupon_amount(Long coupon_amount) {
        this.coupon_amount = coupon_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_start_time
     *
     * @return the value of coupon.coupon_start_time
     *
     * @mbg.generated
     */
    public String getCoupon_start_time() {
        return coupon_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_start_time
     *
     * @param coupon_start_time the value for coupon.coupon_start_time
     *
     * @mbg.generated
     */
    public void setCoupon_start_time(String coupon_start_time) {
        this.coupon_start_time = coupon_start_time == null ? null : coupon_start_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_end_time
     *
     * @return the value of coupon.coupon_end_time
     *
     * @mbg.generated
     */
    public String getCoupon_end_time() {
        return coupon_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_end_time
     *
     * @param coupon_end_time the value for coupon.coupon_end_time
     *
     * @mbg.generated
     */
    public void setCoupon_end_time(String coupon_end_time) {
        this.coupon_end_time = coupon_end_time == null ? null : coupon_end_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_share_url
     *
     * @return the value of coupon.coupon_share_url
     *
     * @mbg.generated
     */
    public String getCoupon_share_url() {
        return coupon_share_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_share_url
     *
     * @param coupon_share_url the value for coupon.coupon_share_url
     *
     * @mbg.generated
     */
    public void setCoupon_share_url(String coupon_share_url) {
        this.coupon_share_url = coupon_share_url == null ? null : coupon_share_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_start_fee
     *
     * @return the value of coupon.coupon_start_fee
     *
     * @mbg.generated
     */
    public String getCoupon_start_fee() {
        return coupon_start_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_start_fee
     *
     * @param coupon_start_fee the value for coupon.coupon_start_fee
     *
     * @mbg.generated
     */
    public void setCoupon_start_fee(String coupon_start_fee) {
        this.coupon_start_fee = coupon_start_fee == null ? null : coupon_start_fee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_total_count
     *
     * @return the value of coupon.coupon_total_count
     *
     * @mbg.generated
     */
    public Long getCoupon_total_count() {
        return coupon_total_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_total_count
     *
     * @param coupon_total_count the value for coupon.coupon_total_count
     *
     * @mbg.generated
     */
    public void setCoupon_total_count(Long coupon_total_count) {
        this.coupon_total_count = coupon_total_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_remain_count
     *
     * @return the value of coupon.coupon_remain_count
     *
     * @mbg.generated
     */
    public Long getCoupon_remain_count() {
        return coupon_remain_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_remain_count
     *
     * @param coupon_remain_count the value for coupon.coupon_remain_count
     *
     * @mbg.generated
     */
    public void setCoupon_remain_count(Long coupon_remain_count) {
        this.coupon_remain_count = coupon_remain_count;
    }
}