package shop.mode;

import java.util.Date;
import shop.mode.extension.MaterialExtension;
import shop.mode.mapper.MaterialMapper;

public class Material extends MaterialExtension implements shop.mode.ORM.POJOMapper<MaterialMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.recommend
     *
     * @mbg.generated
     */
    private Integer recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.up_date_ms
     *
     * @mbg.generated
     */
    private Integer up_date_ms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.deleteAt
     *
     * @mbg.generated
     */
    private Date deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.recommend
     *
     * @return the value of material.recommend
     *
     * @mbg.generated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.recommend
     *
     * @param recommend the value for material.recommend
     *
     * @mbg.generated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.total
     *
     * @return the value of material.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.total
     *
     * @param total the value for material.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.up_date_ms
     *
     * @return the value of material.up_date_ms
     *
     * @mbg.generated
     */
    public Integer getUp_date_ms() {
        return up_date_ms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.up_date_ms
     *
     * @param up_date_ms the value for material.up_date_ms
     *
     * @mbg.generated
     */
    public void setUp_date_ms(Integer up_date_ms) {
        this.up_date_ms = up_date_ms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.deleteAt
     *
     * @return the value of material.deleteAt
     *
     * @mbg.generated
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.deleteAt
     *
     * @param deleteAt the value for material.deleteAt
     *
     * @mbg.generated
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }
}