package shop.mode;

import java.util.Date;
import shop.mode.extension.MaterialItemExtension;
import shop.mode.mapper.MaterialItemMapper;

public class MaterialItem extends MaterialItemExtension implements shop.mode.ORM.POJOMapper<MaterialItemMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_item.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_item.material_id
     *
     * @mbg.generated
     */
    private Long material_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_item.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_item.deleteAt
     *
     * @mbg.generated
     */
    private Date deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_item.name
     *
     * @return the value of material_item.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_item.name
     *
     * @param name the value for material_item.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_item.material_id
     *
     * @return the value of material_item.material_id
     *
     * @mbg.generated
     */
    public Long getMaterial_id() {
        return material_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_item.material_id
     *
     * @param material_id the value for material_item.material_id
     *
     * @mbg.generated
     */
    public void setMaterial_id(Long material_id) {
        this.material_id = material_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_item.pid
     *
     * @return the value of material_item.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_item.pid
     *
     * @param pid the value for material_item.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_item.deleteAt
     *
     * @return the value of material_item.deleteAt
     *
     * @mbg.generated
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_item.deleteAt
     *
     * @param deleteAt the value for material_item.deleteAt
     *
     * @mbg.generated
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }
}