package shop.mode;

import shop.mode.extension.MenuCategoryExtension;
import shop.mode.mapper.MenuCategoryMapper;

public class MenuCategory extends MenuCategoryExtension implements shop.mode.ORM.POJOMapper<MenuCategoryMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_category.recommend
     *
     * @mbg.generated
     */
    private Integer recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_category.name
     *
     * @return the value of menu_category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_category.name
     *
     * @param name the value for menu_category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_category.recommend
     *
     * @return the value of menu_category.recommend
     *
     * @mbg.generated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_category.recommend
     *
     * @param recommend the value for menu_category.recommend
     *
     * @mbg.generated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }
}