package shop.mode;

import shop.mode.extension.ProductExtension;
import shop.mode.mapper.ProductMapper;

public class Product extends ProductExtension implements shop.mode.ORM.POJOMapper<ProductMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated
     */
    private Long category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.coupon_id
     *
     * @mbg.generated
     */
    private String coupon_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sid
     *
     * @mbg.generated
     */
    private Long sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_item_id
     *
     * @mbg.generated
     */
    private Long category_item_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.short_title
     *
     * @mbg.generated
     */
    private String short_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.white_image
     *
     * @mbg.generated
     */
    private String white_image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pict_url
     *
     * @mbg.generated
     */
    private String pict_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.commission_rate
     *
     * @mbg.generated
     */
    private String commission_rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.item_description
     *
     * @mbg.generated
     */
    private String item_description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.volume
     *
     * @mbg.generated
     */
    private Long volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.tk_total_sales
     *
     * @mbg.generated
     */
    private String tk_total_sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.key_word
     *
     * @mbg.generated
     */
    private String key_word;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated
     */
    public Long getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param category_id the value for product.category_id
     *
     * @mbg.generated
     */
    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.coupon_id
     *
     * @return the value of product.coupon_id
     *
     * @mbg.generated
     */
    public String getCoupon_id() {
        return coupon_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.coupon_id
     *
     * @param coupon_id the value for product.coupon_id
     *
     * @mbg.generated
     */
    public void setCoupon_id(String coupon_id) {
        this.coupon_id = coupon_id == null ? null : coupon_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sid
     *
     * @return the value of product.sid
     *
     * @mbg.generated
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sid
     *
     * @param sid the value for product.sid
     *
     * @mbg.generated
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_item_id
     *
     * @return the value of product.category_item_id
     *
     * @mbg.generated
     */
    public Long getCategory_item_id() {
        return category_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_item_id
     *
     * @param category_item_id the value for product.category_item_id
     *
     * @mbg.generated
     */
    public void setCategory_item_id(Long category_item_id) {
        this.category_item_id = category_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.short_title
     *
     * @return the value of product.short_title
     *
     * @mbg.generated
     */
    public String getShort_title() {
        return short_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.short_title
     *
     * @param short_title the value for product.short_title
     *
     * @mbg.generated
     */
    public void setShort_title(String short_title) {
        this.short_title = short_title == null ? null : short_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.white_image
     *
     * @return the value of product.white_image
     *
     * @mbg.generated
     */
    public String getWhite_image() {
        return white_image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.white_image
     *
     * @param white_image the value for product.white_image
     *
     * @mbg.generated
     */
    public void setWhite_image(String white_image) {
        this.white_image = white_image == null ? null : white_image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pict_url
     *
     * @return the value of product.pict_url
     *
     * @mbg.generated
     */
    public String getPict_url() {
        return pict_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pict_url
     *
     * @param pict_url the value for product.pict_url
     *
     * @mbg.generated
     */
    public void setPict_url(String pict_url) {
        this.pict_url = pict_url == null ? null : pict_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.commission_rate
     *
     * @return the value of product.commission_rate
     *
     * @mbg.generated
     */
    public String getCommission_rate() {
        return commission_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.commission_rate
     *
     * @param commission_rate the value for product.commission_rate
     *
     * @mbg.generated
     */
    public void setCommission_rate(String commission_rate) {
        this.commission_rate = commission_rate == null ? null : commission_rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.item_description
     *
     * @return the value of product.item_description
     *
     * @mbg.generated
     */
    public String getItem_description() {
        return item_description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.item_description
     *
     * @param item_description the value for product.item_description
     *
     * @mbg.generated
     */
    public void setItem_description(String item_description) {
        this.item_description = item_description == null ? null : item_description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.volume
     *
     * @return the value of product.volume
     *
     * @mbg.generated
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.volume
     *
     * @param volume the value for product.volume
     *
     * @mbg.generated
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.url
     *
     * @return the value of product.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.url
     *
     * @param url the value for product.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.tk_total_sales
     *
     * @return the value of product.tk_total_sales
     *
     * @mbg.generated
     */
    public String getTk_total_sales() {
        return tk_total_sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.tk_total_sales
     *
     * @param tk_total_sales the value for product.tk_total_sales
     *
     * @mbg.generated
     */
    public void setTk_total_sales(String tk_total_sales) {
        this.tk_total_sales = tk_total_sales == null ? null : tk_total_sales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.key_word
     *
     * @return the value of product.key_word
     *
     * @mbg.generated
     */
    public String getKey_word() {
        return key_word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.key_word
     *
     * @param key_word the value for product.key_word
     *
     * @mbg.generated
     */
    public void setKey_word(String key_word) {
        this.key_word = key_word == null ? null : key_word.trim();
    }
}