package shop.mode;

import shop.mode.extension.ProductImageExtension;
import shop.mode.mapper.ProductImagesMapper;

public class ProductImages extends ProductImageExtension implements shop.mode.ORM.POJOMapper<ProductImagesMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_images.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_images.pic_url
     *
     * @mbg.generated
     */
    private String pic_url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_images.pid
     *
     * @return the value of product_images.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_images.pid
     *
     * @param pid the value for product_images.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_images.pic_url
     *
     * @return the value of product_images.pic_url
     *
     * @mbg.generated
     */
    public String getPic_url() {
        return pic_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_images.pic_url
     *
     * @param pic_url the value for product_images.pic_url
     *
     * @mbg.generated
     */
    public void setPic_url(String pic_url) {
        this.pic_url = pic_url == null ? null : pic_url.trim();
    }
}