package shop.mode;

import java.util.ArrayList;
import java.util.List;
import shop.mode.base.BaseExample;

public class ProductExample implements BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Long value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Long value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Long value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Long value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Long value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Long value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Long> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Long> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Long value1, Long value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Long value1, Long value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andCategory_idIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategory_idIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategory_idEqualTo(Long value) {
            addCriterion("category_id =", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idGreaterThan(Long value) {
            addCriterion("category_id >", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idLessThan(Long value) {
            addCriterion("category_id <", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idIn(List<Long> values) {
            addCriterion("category_id in", values, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "category_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idEqualTo(Integer value) {
            addCriterion("coupon_id =", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotEqualTo(Integer value) {
            addCriterion("coupon_id <>", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThan(Integer value) {
            addCriterion("coupon_id >", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon_id >=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThan(Integer value) {
            addCriterion("coupon_id <", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThanOrEqualTo(Integer value) {
            addCriterion("coupon_id <=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIn(List<Integer> values) {
            addCriterion("coupon_id in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotIn(List<Integer> values) {
            addCriterion("coupon_id not in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idBetween(Integer value1, Integer value2) {
            addCriterion("coupon_id between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon_id not between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Long value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Long value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Long value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Long value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Long value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Long value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Long> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Long> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Long value1, Long value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Long value1, Long value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idIsNull() {
            addCriterion("category_item_id is null");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idIsNotNull() {
            addCriterion("category_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idEqualTo(Long value) {
            addCriterion("category_item_id =", value, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idNotEqualTo(Long value) {
            addCriterion("category_item_id <>", value, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idGreaterThan(Long value) {
            addCriterion("category_item_id >", value, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idGreaterThanOrEqualTo(Long value) {
            addCriterion("category_item_id >=", value, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idLessThan(Long value) {
            addCriterion("category_item_id <", value, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idLessThanOrEqualTo(Long value) {
            addCriterion("category_item_id <=", value, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idIn(List<Long> values) {
            addCriterion("category_item_id in", values, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idNotIn(List<Long> values) {
            addCriterion("category_item_id not in", values, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idBetween(Long value1, Long value2) {
            addCriterion("category_item_id between", value1, value2, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andCategory_item_idNotBetween(Long value1, Long value2) {
            addCriterion("category_item_id not between", value1, value2, "category_item_id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andShort_titleIsNull() {
            addCriterion("short_title is null");
            return (Criteria) this;
        }

        public Criteria andShort_titleIsNotNull() {
            addCriterion("short_title is not null");
            return (Criteria) this;
        }

        public Criteria andShort_titleEqualTo(String value) {
            addCriterion("short_title =", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleNotEqualTo(String value) {
            addCriterion("short_title <>", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleGreaterThan(String value) {
            addCriterion("short_title >", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleGreaterThanOrEqualTo(String value) {
            addCriterion("short_title >=", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleLessThan(String value) {
            addCriterion("short_title <", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleLessThanOrEqualTo(String value) {
            addCriterion("short_title <=", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleLike(String value) {
            addCriterion("short_title like", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleNotLike(String value) {
            addCriterion("short_title not like", value, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleIn(List<String> values) {
            addCriterion("short_title in", values, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleNotIn(List<String> values) {
            addCriterion("short_title not in", values, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleBetween(String value1, String value2) {
            addCriterion("short_title between", value1, value2, "short_title");
            return (Criteria) this;
        }

        public Criteria andShort_titleNotBetween(String value1, String value2) {
            addCriterion("short_title not between", value1, value2, "short_title");
            return (Criteria) this;
        }

        public Criteria andWhite_imageIsNull() {
            addCriterion("white_image is null");
            return (Criteria) this;
        }

        public Criteria andWhite_imageIsNotNull() {
            addCriterion("white_image is not null");
            return (Criteria) this;
        }

        public Criteria andWhite_imageEqualTo(String value) {
            addCriterion("white_image =", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageNotEqualTo(String value) {
            addCriterion("white_image <>", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageGreaterThan(String value) {
            addCriterion("white_image >", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageGreaterThanOrEqualTo(String value) {
            addCriterion("white_image >=", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageLessThan(String value) {
            addCriterion("white_image <", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageLessThanOrEqualTo(String value) {
            addCriterion("white_image <=", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageLike(String value) {
            addCriterion("white_image like", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageNotLike(String value) {
            addCriterion("white_image not like", value, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageIn(List<String> values) {
            addCriterion("white_image in", values, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageNotIn(List<String> values) {
            addCriterion("white_image not in", values, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageBetween(String value1, String value2) {
            addCriterion("white_image between", value1, value2, "white_image");
            return (Criteria) this;
        }

        public Criteria andWhite_imageNotBetween(String value1, String value2) {
            addCriterion("white_image not between", value1, value2, "white_image");
            return (Criteria) this;
        }

        public Criteria andPict_urlIsNull() {
            addCriterion("pict_url is null");
            return (Criteria) this;
        }

        public Criteria andPict_urlIsNotNull() {
            addCriterion("pict_url is not null");
            return (Criteria) this;
        }

        public Criteria andPict_urlEqualTo(String value) {
            addCriterion("pict_url =", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlNotEqualTo(String value) {
            addCriterion("pict_url <>", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlGreaterThan(String value) {
            addCriterion("pict_url >", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlGreaterThanOrEqualTo(String value) {
            addCriterion("pict_url >=", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlLessThan(String value) {
            addCriterion("pict_url <", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlLessThanOrEqualTo(String value) {
            addCriterion("pict_url <=", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlLike(String value) {
            addCriterion("pict_url like", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlNotLike(String value) {
            addCriterion("pict_url not like", value, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlIn(List<String> values) {
            addCriterion("pict_url in", values, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlNotIn(List<String> values) {
            addCriterion("pict_url not in", values, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlBetween(String value1, String value2) {
            addCriterion("pict_url between", value1, value2, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPict_urlNotBetween(String value1, String value2) {
            addCriterion("pict_url not between", value1, value2, "pict_url");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Float value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Float value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Float value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Float value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Float value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Float> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Float> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Float value1, Float value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Float value1, Float value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCommission_rateIsNull() {
            addCriterion("commission_rate is null");
            return (Criteria) this;
        }

        public Criteria andCommission_rateIsNotNull() {
            addCriterion("commission_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCommission_rateEqualTo(String value) {
            addCriterion("commission_rate =", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateNotEqualTo(String value) {
            addCriterion("commission_rate <>", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateGreaterThan(String value) {
            addCriterion("commission_rate >", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateGreaterThanOrEqualTo(String value) {
            addCriterion("commission_rate >=", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateLessThan(String value) {
            addCriterion("commission_rate <", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateLessThanOrEqualTo(String value) {
            addCriterion("commission_rate <=", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateLike(String value) {
            addCriterion("commission_rate like", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateNotLike(String value) {
            addCriterion("commission_rate not like", value, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateIn(List<String> values) {
            addCriterion("commission_rate in", values, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateNotIn(List<String> values) {
            addCriterion("commission_rate not in", values, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateBetween(String value1, String value2) {
            addCriterion("commission_rate between", value1, value2, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andCommission_rateNotBetween(String value1, String value2) {
            addCriterion("commission_rate not between", value1, value2, "commission_rate");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionIsNull() {
            addCriterion("item_description is null");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionIsNotNull() {
            addCriterion("item_description is not null");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionEqualTo(String value) {
            addCriterion("item_description =", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionNotEqualTo(String value) {
            addCriterion("item_description <>", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionGreaterThan(String value) {
            addCriterion("item_description >", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionGreaterThanOrEqualTo(String value) {
            addCriterion("item_description >=", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionLessThan(String value) {
            addCriterion("item_description <", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionLessThanOrEqualTo(String value) {
            addCriterion("item_description <=", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionLike(String value) {
            addCriterion("item_description like", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionNotLike(String value) {
            addCriterion("item_description not like", value, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionIn(List<String> values) {
            addCriterion("item_description in", values, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionNotIn(List<String> values) {
            addCriterion("item_description not in", values, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionBetween(String value1, String value2) {
            addCriterion("item_description between", value1, value2, "item_description");
            return (Criteria) this;
        }

        public Criteria andItem_descriptionNotBetween(String value1, String value2) {
            addCriterion("item_description not between", value1, value2, "item_description");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Long value) {
            addCriterion("volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Long value) {
            addCriterion("volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Long value) {
            addCriterion("volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Long value) {
            addCriterion("volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Long value) {
            addCriterion("volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Long value) {
            addCriterion("volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Long> values) {
            addCriterion("volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Long> values) {
            addCriterion("volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Long value1, Long value2) {
            addCriterion("volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Long value1, Long value2) {
            addCriterion("volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesIsNull() {
            addCriterion("tk_total_sales is null");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesIsNotNull() {
            addCriterion("tk_total_sales is not null");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesEqualTo(String value) {
            addCriterion("tk_total_sales =", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesNotEqualTo(String value) {
            addCriterion("tk_total_sales <>", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesGreaterThan(String value) {
            addCriterion("tk_total_sales >", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesGreaterThanOrEqualTo(String value) {
            addCriterion("tk_total_sales >=", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesLessThan(String value) {
            addCriterion("tk_total_sales <", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesLessThanOrEqualTo(String value) {
            addCriterion("tk_total_sales <=", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesLike(String value) {
            addCriterion("tk_total_sales like", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesNotLike(String value) {
            addCriterion("tk_total_sales not like", value, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesIn(List<String> values) {
            addCriterion("tk_total_sales in", values, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesNotIn(List<String> values) {
            addCriterion("tk_total_sales not in", values, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesBetween(String value1, String value2) {
            addCriterion("tk_total_sales between", value1, value2, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andTk_total_salesNotBetween(String value1, String value2) {
            addCriterion("tk_total_sales not between", value1, value2, "tk_total_sales");
            return (Criteria) this;
        }

        public Criteria andKey_wordIsNull() {
            addCriterion("key_word is null");
            return (Criteria) this;
        }

        public Criteria andKey_wordIsNotNull() {
            addCriterion("key_word is not null");
            return (Criteria) this;
        }

        public Criteria andKey_wordEqualTo(String value) {
            addCriterion("key_word =", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordNotEqualTo(String value) {
            addCriterion("key_word <>", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordGreaterThan(String value) {
            addCriterion("key_word >", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordGreaterThanOrEqualTo(String value) {
            addCriterion("key_word >=", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordLessThan(String value) {
            addCriterion("key_word <", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordLessThanOrEqualTo(String value) {
            addCriterion("key_word <=", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordLike(String value) {
            addCriterion("key_word like", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordNotLike(String value) {
            addCriterion("key_word not like", value, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordIn(List<String> values) {
            addCriterion("key_word in", values, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordNotIn(List<String> values) {
            addCriterion("key_word not in", values, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordBetween(String value1, String value2) {
            addCriterion("key_word between", value1, value2, "key_word");
            return (Criteria) this;
        }

        public Criteria andKey_wordNotBetween(String value1, String value2) {
            addCriterion("key_word not between", value1, value2, "key_word");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}