package shop.mode;

import shop.mode.extension.RecommendExtension;
import shop.mode.mapper.RecommendMapper;

public class Recommend extends RecommendExtension implements shop.mode.ORM.POJOMapper<RecommendMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.is_recommend
     *
     * @mbg.generated
     */
    private Integer is_recommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.pid
     *
     * @return the value of recommend.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.pid
     *
     * @param pid the value for recommend.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.is_recommend
     *
     * @return the value of recommend.is_recommend
     *
     * @mbg.generated
     */
    public Integer getIs_recommend() {
        return is_recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.is_recommend
     *
     * @param is_recommend the value for recommend.is_recommend
     *
     * @mbg.generated
     */
    public void setIs_recommend(Integer is_recommend) {
        this.is_recommend = is_recommend;
    }
}