package shop.mode;

import shop.mode.extension.ShopUserExtension;
import shop.mode.mapper.ShopUserMapper;

public class ShopUser extends ShopUserExtension implements shop.mode.ORM.POJOMapper<ShopUserMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.sid
     *
     * @mbg.generated
     */
    private Long sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.provcity
     *
     * @mbg.generated
     */
    private String provcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.shop_dsr
     *
     * @mbg.generated
     */
    private Long shop_dsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.shop_title
     *
     * @mbg.generated
     */
    private String shop_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.user_type
     *
     * @mbg.generated
     */
    private Long user_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.nick
     *
     * @mbg.generated
     */
    private String nick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.sid
     *
     * @return the value of shop_user.sid
     *
     * @mbg.generated
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.sid
     *
     * @param sid the value for shop_user.sid
     *
     * @mbg.generated
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.provcity
     *
     * @return the value of shop_user.provcity
     *
     * @mbg.generated
     */
    public String getProvcity() {
        return provcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.provcity
     *
     * @param provcity the value for shop_user.provcity
     *
     * @mbg.generated
     */
    public void setProvcity(String provcity) {
        this.provcity = provcity == null ? null : provcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.shop_dsr
     *
     * @return the value of shop_user.shop_dsr
     *
     * @mbg.generated
     */
    public Long getShop_dsr() {
        return shop_dsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.shop_dsr
     *
     * @param shop_dsr the value for shop_user.shop_dsr
     *
     * @mbg.generated
     */
    public void setShop_dsr(Long shop_dsr) {
        this.shop_dsr = shop_dsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.shop_title
     *
     * @return the value of shop_user.shop_title
     *
     * @mbg.generated
     */
    public String getShop_title() {
        return shop_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.shop_title
     *
     * @param shop_title the value for shop_user.shop_title
     *
     * @mbg.generated
     */
    public void setShop_title(String shop_title) {
        this.shop_title = shop_title == null ? null : shop_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.user_type
     *
     * @return the value of shop_user.user_type
     *
     * @mbg.generated
     */
    public Long getUser_type() {
        return user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.user_type
     *
     * @param user_type the value for shop_user.user_type
     *
     * @mbg.generated
     */
    public void setUser_type(Long user_type) {
        this.user_type = user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.nick
     *
     * @return the value of shop_user.nick
     *
     * @mbg.generated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.nick
     *
     * @param nick the value for shop_user.nick
     *
     * @mbg.generated
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }
}