package shop.mode;

import java.util.Date;
import shop.mode.extension.UserExtension;
import shop.mode.mapper.UserMapper;

public class User extends UserExtension implements shop.mode.ORM.POJOMapper<UserMapper> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openID
     *
     * @mbg.generated
     */
    private Integer openID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.group_
     *
     * @mbg.generated
     */
    private String group_;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.deleteAt
     *
     * @mbg.generated
     */
    private Date deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openID
     *
     * @return the value of user.openID
     *
     * @mbg.generated
     */
    public Integer getOpenID() {
        return openID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openID
     *
     * @param openID the value for user.openID
     *
     * @mbg.generated
     */
    public void setOpenID(Integer openID) {
        this.openID = openID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.group_
     *
     * @return the value of user.group_
     *
     * @mbg.generated
     */
    public String getGroup_() {
        return group_;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.group_
     *
     * @param group_ the value for user.group_
     *
     * @mbg.generated
     */
    public void setGroup_(String group_) {
        this.group_ = group_ == null ? null : group_.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.deleteAt
     *
     * @return the value of user.deleteAt
     *
     * @mbg.generated
     */
    public Date getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.deleteAt
     *
     * @param deleteAt the value for user.deleteAt
     *
     * @mbg.generated
     */
    public void setDeleteAt(Date deleteAt) {
        this.deleteAt = deleteAt;
    }
}