package shop.mode.mapper;

import java.util.List;
import shop.mode.CategoryItem;
import shop.mode.CategoryItemExample;

public interface CategoryItemMapper extends BaseMapper<CategoryItem, CategoryItemExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    int insert(CategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    int insertSelective(CategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    List<CategoryItem> selectByExample(CategoryItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    CategoryItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryItem record);
}