package shop.mode.mapper;

import java.util.List;
import shop.mode.MaterialItem;
import shop.mode.MaterialItemExample;

public interface MaterialItemMapper extends BaseMapper<MaterialItem, MaterialItemExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    int insert(MaterialItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    int insertSelective(MaterialItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    List<MaterialItem> selectByExample(MaterialItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    MaterialItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MaterialItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialItem record);
}