package shop.mode.mapper;

import java.util.List;
import shop.mode.MenuCategory;
import shop.mode.MenuCategoryExample;

public interface MenuCategoryMapper extends BaseMapper<MenuCategory, MenuCategoryExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    int insert(MenuCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    int insertSelective(MenuCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    List<MenuCategory> selectByExample(MenuCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    MenuCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuCategory record);
}