package shop.mode.mapper;

import java.util.List;
import shop.mode.ProductImages;
import shop.mode.ProductImagesExample;

public interface ProductImagesMapper extends BaseMapper<ProductImages, ProductImagesExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    int insert(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    int insertSelective(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    List<ProductImages> selectByExample(ProductImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    ProductImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductImages record);
}