package shop.mode.mapper;

import java.util.List;
import shop.mode.SearchHistory;
import shop.mode.SearchHistoryExample;

public interface SearchHistoryMapper extends BaseMapper<SearchHistory, SearchHistoryExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    int insert(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    int insertSelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    List<SearchHistory> selectByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    SearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_key_word
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SearchHistory record);
}